version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stellariq_db
      POSTGRES_USER: stellariq
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stellariq -d stellariq_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  valkey:
    image: valkey/valkey:8.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  valkey_data:
