"""add_notification_tables

Revision ID: 0019d798a454
Revises: 9b7cdfaa2f7e
Create Date: 2025-09-22 15:11:28.829530

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0019d798a454"
down_revision = "9b7cdfaa2f7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
