"""Add refresh token fields to users table

Revision ID: 00bdb1b5f6bc
Revises: b4e7e877ac14
Create Date: 2025-09-16 15:44:08.971059

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "00bdb1b5f6bc"
down_revision = "b4e7e877ac14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
