"""create_notification_tables

Revision ID: 00c9459617c5
Revises: 0019d798a454
Create Date: 2025-09-22 15:32:04.185797

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "00c9459617c5"
down_revision = "0019d798a454"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
