"""Add disclaimer agreement fields to users table

Revision ID: 07029ea340ee
Revises: 09f04dd11024
Create Date: 2025-09-18 14:09:53.836248

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "07029ea340ee"
down_revision = "09f04dd11024"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add disclaimer fields with proper defaults
    op.add_column(
        "users",
        sa.Column(
            "agreed_to_disclaimer", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "users",
        sa.Column("disclaimer_agreed_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Update existing users to have agreed to disclaimer for backward compatibility
    op.execute(
        "UPDATE users SET agreed_to_disclaimer = true, disclaimer_agreed_at = created_at WHERE agreed_to_disclaimer = false"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "disclaimer_agreed_at")
    op.drop_column("users", "agreed_to_disclaimer")
    # ### end Alembic commands ###
