"""Add crypto portfolio table

Revision ID: 09f04dd11024
Revises: 5a6b9210c7d4
Create Date: 2025-09-16 20:44:42.687428

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "09f04dd11024"
down_revision = "5a6b9210c7d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_portfolio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("average_buy_price", sa.Float(), nullable=True),
        sa.Column("current_price", sa.Float(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("profit_loss", sa.Float(), nullable=True),
        sa.Column("profit_loss_percentage", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_price_update", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "symbol", name="_user_symbol_uc"),
    )
    op.create_index(
        op.f("ix_crypto_portfolio_created_at"),
        "crypto_portfolio",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crypto_portfolio_id"), "crypto_portfolio", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_crypto_portfolio_symbol"), "crypto_portfolio", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_crypto_portfolio_user_id"),
        "crypto_portfolio",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crypto_portfolio_user_id"), table_name="crypto_portfolio")
    op.drop_index(op.f("ix_crypto_portfolio_symbol"), table_name="crypto_portfolio")
    op.drop_index(op.f("ix_crypto_portfolio_id"), table_name="crypto_portfolio")
    op.drop_index(op.f("ix_crypto_portfolio_created_at"), table_name="crypto_portfolio")
    op.drop_table("crypto_portfolio")
    # ### end Alembic commands ###
