"""Add account deletion requests table

Revision ID: 4b038b1ec8a1
Revises: 7454305329f1
Create Date: 2025-09-26 22:10:14.011230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b038b1ec8a1'
down_revision = '7454305329f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
