"""Create account deletion requests table

Revision ID: 500deabc123a
Revises: 83966a3c89d5
Create Date: 2025-09-26 22:59:25.091460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500deabc123a'
down_revision = '83966a3c89d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_EMAIL_CONFIRMATION', 'EMAIL_CONFIRMED', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='deletionstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('confirmation_token', sa.String(), nullable=True),
    sa.Column('confirmation_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.String(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_deletion_requests_confirmation_token'), 'account_deletion_requests', ['confirmation_token'], unique=True)
    op.create_index(op.f('ix_account_deletion_requests_email'), 'account_deletion_requests', ['email'], unique=False)
    op.create_index(op.f('ix_account_deletion_requests_id'), 'account_deletion_requests', ['id'], unique=False)
    op.create_index(op.f('ix_account_deletion_requests_request_id'), 'account_deletion_requests', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_deletion_requests_request_id'), table_name='account_deletion_requests')
    op.drop_index(op.f('ix_account_deletion_requests_id'), table_name='account_deletion_requests')
    op.drop_index(op.f('ix_account_deletion_requests_email'), table_name='account_deletion_requests')
    op.drop_index(op.f('ix_account_deletion_requests_confirmation_token'), table_name='account_deletion_requests')
    op.drop_table('account_deletion_requests')
    # ### end Alembic commands ###
