"""add_notification_models

Revision ID: 58e38bcdfbc6
Revises: 00c9459617c5
Create Date: 2025-09-22 15:50:11.194768

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "58e38bcdfbc6"
down_revision = "00c9459617c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "device_type",
            sa.Enum("IOS", "ANDROID", "WEB", name="devicetype"),
            nullable=False,
        ),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("device_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_tokens_id"), "device_tokens", ["id"], unique=False)
    op.create_index(
        op.f("ix_device_tokens_token"), "device_tokens", ["token"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("favorite_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum("MARKET_ALERT", "PRICE_ALERT", "SYSTEM", name="notificationtype"),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("PUSH", "EMAIL", "SMS", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("market_condition", sa.String(), nullable=True),
        sa.Column("confidence_score", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", "READ", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["favorite_id"],
            ["favorites.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_symbol"), "notifications", ["symbol"], unique=False
    )
    op.add_column(
        "favorites", sa.Column("last_alert_state", sa.String(), nullable=True)
    )
    op.add_column(
        "favorites",
        sa.Column("last_alert_sent", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("favorites", "updated_at")
    op.drop_column("favorites", "last_alert_sent_at")
    op.drop_column("favorites", "last_alert_condition")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorites",
        sa.Column(
            "last_alert_condition", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "favorites",
        sa.Column(
            "last_alert_sent_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "favorites",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("favorites", "last_alert_sent")
    op.drop_column("favorites", "last_alert_state")
    op.drop_index(op.f("ix_notifications_symbol"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_device_tokens_token"), table_name="device_tokens")
    op.drop_index(op.f("ix_device_tokens_id"), table_name="device_tokens")
    op.drop_table("device_tokens")
    # ### end Alembic commands ###
