"""Add password reset fields to users table

Revision ID: 5a6b9210c7d4
Revises: 00bdb1b5f6bc
Create Date: 2025-09-16 17:04:25.559703

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5a6b9210c7d4"
down_revision = "00bdb1b5f6bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_reset_token", sa.Text(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "password_reset_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_expires_at")
    op.drop_column("users", "password_reset_token")
    # ### end Alembic commands ###
