"""add_price_alert_fields_to_favorites

Revision ID: 7454305329f1
Revises: 58e38bcdfbc6
Create Date: 2025-09-24 14:47:08.800753

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7454305329f1"
down_revision = "58e38bcdfbc6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorites",
        sa.Column(
            "price_alert_enabled", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    op.add_column(
        "favorites", sa.Column("alert_price_above", sa.Float(), nullable=True)
    )
    op.add_column(
        "favorites", sa.Column("alert_price_below", sa.Float(), nullable=True)
    )
    op.add_column(
        "favorites",
        sa.Column("last_price_alert_sent", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorites", "last_price_alert_sent")
    op.drop_column("favorites", "alert_price_below")
    op.drop_column("favorites", "alert_price_above")
    op.drop_column("favorites", "price_alert_enabled")
    # ### end Alembic commands ###
