"""Add email confirmation fields to account deletion requests

Revision ID: 83966a3c89d5
Revises: 4b038b1ec8a1
Create Date: 2025-09-26 22:37:35.738507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83966a3c89d5'
down_revision = '4b038b1ec8a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
