"""add_alert_fields_to_favorites

Revision ID: 9b7cdfaa2f7e
Revises: d34e07c56118
Create Date: 2025-09-22 14:55:33.237341

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b7cdfaa2f7e"
down_revision = "d34e07c56118"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("favorites", sa.Column("alert_enabled", sa.Boolean(), nullable=False))
    op.add_column(
        "favorites", sa.Column("alert_on_overbought", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "favorites", sa.Column("alert_on_oversold", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "favorites", sa.Column("alert_on_neutral", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "favorites", sa.Column("last_alert_condition", sa.String(), nullable=True)
    )
    op.add_column(
        "favorites",
        sa.Column("last_alert_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "favorites",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorites", "updated_at")
    op.drop_column("favorites", "last_alert_sent_at")
    op.drop_column("favorites", "last_alert_condition")
    op.drop_column("favorites", "alert_on_neutral")
    op.drop_column("favorites", "alert_on_oversold")
    op.drop_column("favorites", "alert_on_overbought")
    op.drop_column("favorites", "alert_enabled")
    # ### end Alembic commands ###
