"""Add refresh token fields to users table

Revision ID: b4e7e877ac14
Revises: b6b7fb8591b3
Create Date: 2025-09-16 14:49:36.963484

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4e7e877ac14"
down_revision = "b6b7fb8591b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("refresh_token", sa.Text(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "refresh_token_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token_expires_at")
    op.drop_column("users", "refresh_token")
    # ### end Alembic commands ###
