"""Add user profile fields

Revision ID: d34e07c56118
Revises: 07029ea340ee
Create Date: 2025-09-18 14:40:40.723149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d34e07c56118"
down_revision = "07029ea340ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add profile fields with proper defaults for existing users
    op.add_column("users", sa.Column("full_name", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("timezone", sa.String(), nullable=False, server_default="UTC"),
    )
    op.add_column(
        "users",
        sa.Column(
            "preferred_currency", sa.String(), nullable=False, server_default="USD"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_notifications", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "push_notifications", sa.Boolean(), nullable=False, server_default="true"
        ),
    )

    # Update existing users with default values
    op.execute("UPDATE users SET timezone = 'UTC' WHERE timezone IS NULL")
    op.execute(
        "UPDATE users SET preferred_currency = 'USD' WHERE preferred_currency IS NULL"
    )
    op.execute(
        "UPDATE users SET email_notifications = true WHERE email_notifications IS NULL"
    )
    op.execute(
        "UPDATE users SET push_notifications = true WHERE push_notifications IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "push_notifications")
    op.drop_column("users", "email_notifications")
    op.drop_column("users", "preferred_currency")
    op.drop_column("users", "timezone")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
